databases:
  - name: tunnelbrawl
    databaseName: tunnelbrawl
    user: tunnelbrawl

services:
  - type: web
    name: tunnelbrawl
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tunnelbrawl
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false